kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
