apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: <storage-node-ip>
  ports:
  - port: 1
- addresses:
  - ip: <storage-node-ip>
  ports:
  - port: 1
- addresses:
  - ip: <storage-node-ip>
  ports:
  - port: 1
