apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 7Gi
    selector:
      matchLabels:
        storage-tier: gluster
